version: '3'
services:
  foo:
    container_name: sandbox-server-foo
    build: ../../resources/foo
    ports:
    - '10000:10000'
  bar:
    container_name: sandbox-server-bar
    build: ../../resources/bar
    ports:
    - '10001:10000'
  target:
    container_name: sandbox-target-one
    build: .
    ports:
    - '10002:10002'
    depends_on:
    - foo
    - bar
